## main settings
name: Twitter ActivityPub Bridge
domain: localhost
port: 3000
useQueueDashboard: false

## mongodb
db:
  host: localhost
  port: 27017
  name: twitter-activitypub-bridge

## redis
redis:
  host: localhost
  port: 6379
  # password: example
  # db: 0

## twitter
twitter:
  consumer_key:
  consumer_secret:
  access_token: 
  access_token_secret:
  # list_prefix: bridge-

## maintainer
maintainer:
  name: "" # your name
  email: "" # your email

## ignore user/instance
ignoreList:
  - "@proxy@*" # Ignore certain users, regardless of instance
  - "@*@example.instance" # Ignore certain instance, regardless of user
  - "@proxy@example.instance" # Ignore certain users of a particular instance